#pragma once
#include "String.h"
#define LEFT_SQUARE_BRACKET_UPPER_CORNER String("\u23A1")
#define LEFT_SQUARE_BRACKET_EXTENSION String("\u23A2")
#define LEFT_SQUARE_BRACKET_LOWER_CORNER String("\u23A3")
#define RIGHT_SQUARE_BRACKET_UPPER_CORNER String("\u23A4")
#define RIGHT_SQUARE_BRACKET_EXTENSION String("\u23A5")
#define RIGHT_SQUARE_BRACKET_LOWER_CORNER String("\u23A6")
#define LEFT_SQUARE_BRACKET String("\u005B")
#define RIGHT_SQUARE_BRACKET String("\u005D")
// Unused symbols
// #define LEFT_POINTING_ANGLE_BRACKET String("\u2329")
// #define RIGHT_POINTING_ANGLE_BRACKET String("\u232A")